### ISSUE TITLE
QuastCombine Dockerfile - Tkinter display error

### ISSUE THREAD

**Issue by erpangilinan** [erpangilinan/file-rename#1]
While trying to create a Dockerfile for QuastCombine.py: matplotlib is not able to function
1) DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends wget python3 python3-matplotlib
Missing module: Tkinter not found
-next test with download python3-matplotlib with additional pre-reqs
-possibly test: "apt-get install -y python3-tk"

2)DEBIAN_FRONTEND=noninteractive apt-get install -y wget python3 python3-matplotlib
"_tkinter.TclError: no display name and no $DISPLAY environment variable"

```
root@e8d2ff365882:/tmp# ./QuastCombine.py test_abyss.html 
Traceback (most recent call last):
  File "./QuastCombine.py", line 560, in <module>
    DataOut()
  File "./QuastCombine.py", line 178, in DataOut
    CreateGraph(Graphcontents)
  File "./QuastCombine.py", line 483, in CreateGraph
    CombineGraph(plot, plotlabels)
  File "./QuastCombine.py", line 492, in CombineGraph
    plt.plot(list[1], list[0], label = getattr(data, "Name"))
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 3250, in plot
    ax = gca()
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 962, in gca
    return gcf().gca(**kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 592, in gcf
    return figure()
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 539, in figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by erpangilinan** [comment]
https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

Inserted this code to right before pyplot was imported, but not at the very top as suggested. Will push and test in Docker to see if it works.
```
import matplotlib
matplotlib.use('Agg')
```
